//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate_Common
    {
        public int Estimate_Id { get; set; }
        public int Employee_Id { get; set; }
        public string Technology_Name { get; set; }
        public string Region { get; set; }
        public System.DateTime Creation_date { get; set; }
        public string Estimate_Status { get; set; }
        public Nullable<System.DateTime> Finish_date { get; set; }
    }
}
