//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExperimentEntities111 : DbContext
    {
        public ExperimentEntities111()
            : base("name=ExperimentEntities111")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estimate_Common> Estimate_Common { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<WebSite> WebSites { get; set; }
        public virtual DbSet<USER_REGIONS> USER_REGIONS { get; set; }
    
        public virtual ObjectResult<Nullable<int>> f_Test_Emp(Nullable<int> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f_Test_Emp", param1Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f_Test_Estimate(Nullable<int> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f_Test_Estimate", param1Parameter);
        }
    
        public virtual int USER_REGION(string eid, string region)
        {
            var eidParameter = eid != null ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USER_REGION", eidParameter, regionParameter);
        }
    
        public virtual int USER_REGIONS_SP(string eid, string region)
        {
            var eidParameter = eid != null ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USER_REGIONS_SP", eidParameter, regionParameter);
        }
    }
}
