//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int Id { get; set; }
        public int e_Id { get; set; }
        public string Technology_name { get; set; }
        public string Region { get; set; }
        public string Operation_name { get; set; }
        public double Time_Taken { get; set; }
    }
}
