//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_REGIONS1
    {
        public string EMPLOYEE_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public string REGION { get; set; }
    }
}
