//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UOP_YES1QEntities1 : DbContext
    {
        public UOP_YES1QEntities1()
            : base("name=UOP_YES1QEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<YES_APPLICATION_USER> YES_APPLICATION_USER { get; set; }
        public virtual DbSet<YES_ESTIMATE_COMMON> YES_ESTIMATE_COMMON { get; set; }
        public virtual DbSet<YES_CUSTOMER> YES_CUSTOMER { get; set; }
        public virtual DbSet<YES_Instrumentation> YES_Instrumentation { get; set; }
        public virtual DbSet<YES_LOCATION> YES_LOCATION { get; set; }
        public virtual DbSet<YES_LOG_TIME> YES_LOG_TIME { get; set; }
    
        public virtual ObjectResult<f_Test_Procedure_try6_Result> f_Test_Procedure_try6(string param1, string param3)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(string));
    
            var param3Parameter = param3 != null ?
                new ObjectParameter("param3", param3) :
                new ObjectParameter("param3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_Test_Procedure_try6_Result>("f_Test_Procedure_try6", param1Parameter, param3Parameter);
        }
    
        public virtual ObjectResult<string> f_Test_Procedure_Region()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f_Test_Procedure_Region");
        }
    
        public virtual ObjectResult<SP_Estimate_common1_Result> SP_Estimate_common1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Estimate_common1_Result>("SP_Estimate_common1");
        }
    
        public virtual ObjectResult<Report_sp_Result> Report_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_sp_Result>("Report_sp");
        }
    
        public virtual ObjectResult<Report_sp1_Result> Report_sp1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_sp1_Result>("Report_sp1");
        }
    
        public virtual ObjectResult<Report_sp_final_Result> Report_sp_final()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_sp_final_Result>("Report_sp_final");
        }
    
        public virtual ObjectResult<Dashboard_MonthlyReport_SP_Result> Dashboard_MonthlyReport_SP(Nullable<int> time, string tech)
        {
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(int));
    
            var techParameter = tech != null ?
                new ObjectParameter("tech", tech) :
                new ObjectParameter("tech", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dashboard_MonthlyReport_SP_Result>("Dashboard_MonthlyReport_SP", timeParameter, techParameter);
        }
    
        public virtual ObjectResult<Dashboard_EstimatorReport_SP_Result> Dashboard_EstimatorReport_SP(Nullable<int> time, string tech)
        {
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(int));
    
            var techParameter = tech != null ?
                new ObjectParameter("tech", tech) :
                new ObjectParameter("tech", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dashboard_EstimatorReport_SP_Result>("Dashboard_EstimatorReport_SP", timeParameter, techParameter);
        }
    
        public virtual ObjectResult<Dashboard_AllEstmates_SP_Result1> Dashboard_AllEstmates_SP(string tech, Nullable<int> time, string status)
        {
            var techParameter = tech != null ?
                new ObjectParameter("tech", tech) :
                new ObjectParameter("tech", typeof(string));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dashboard_AllEstmates_SP_Result1>("Dashboard_AllEstmates_SP", techParameter, timeParameter, statusParameter);
        }
    
        public virtual ObjectResult<Dashboard_MonthlyReport_SP1_Result> Dashboard_MonthlyReport_SP1(Nullable<System.DateTime> time1, Nullable<System.DateTime> time2, string tech)
        {
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            var techParameter = tech != null ?
                new ObjectParameter("tech", tech) :
                new ObjectParameter("tech", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dashboard_MonthlyReport_SP1_Result>("Dashboard_MonthlyReport_SP1", time1Parameter, time2Parameter, techParameter);
        }
    
        public virtual ObjectResult<DASHBOARD_CHART_ALLTECH_SP_Result> DASHBOARD_CHART_ALLTECH_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DASHBOARD_CHART_ALLTECH_SP_Result>("DASHBOARD_CHART_ALLTECH_SP");
        }
    }
}
