//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YES_ESTIMATE_COMMON
    {
        public int ESTIMATE_ID_SQ { get; set; }
        public Nullable<int> REQUEST_ID { get; set; }
        public string ESTIMATION_DESC { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public string TECHNOLOGY_CD { get; set; }
        public string ESTIMATED_BY_ID { get; set; }
        public string YE_REVISION_IND { get; set; }
        public Nullable<System.DateTime> ESTIMATE_ASSIGNED_DT { get; set; }
        public Nullable<System.DateTime> ESTIMATE_ISSUE_DT { get; set; }
        public string REQUEST_ESTIMATE_STATUS_CD { get; set; }
        public Nullable<decimal> ESTIMATE_HOUR_PRD { get; set; }
        public Nullable<decimal> OTHER_HOUR_PRD { get; set; }
        public string DESIGN_BASIS_IND { get; set; }
        public string ESTIMATE_TO_CUSTOMER_IND { get; set; }
        public string DELETE_IND { get; set; }
        public string UNIT_PREFERENCE_CD { get; set; }
        public string PURPOSE_CD { get; set; }
        public string CREATED_BY_USER_ID { get; set; }
        public System.DateTime CREATED_ON_DT { get; set; }
        public string UPDATED_BY_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATED_ON_DT { get; set; }
        public string SYNC_BY_USER_ID { get; set; }
        public Nullable<System.DateTime> SYNC_ON_DT { get; set; }
        public string BASE_CASE_IND { get; set; }
        public Nullable<int> LPI_TECHO_EST_ID { get; set; }
    
        public virtual YES_APPLICATION_USER YES_APPLICATION_USER { get; set; }
    }
}
