//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YES_APPLICATION_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YES_APPLICATION_USER()
        {
            this.YES_ESTIMATE_COMMON = new HashSet<YES_ESTIMATE_COMMON>();
            this.YES_LOG_TIME = new HashSet<YES_LOG_TIME>();
            this.YES_LOG_TIME1 = new HashSet<YES_LOG_TIME>();
            this.YES_LOG_TIME2 = new HashSet<YES_LOG_TIME>();
        }
    
        public string EMPLOYEE_ID { get; set; }
        public string FIRST_NM { get; set; }
        public string MIDDLE_NM { get; set; }
        public string LAST_NM { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string DISPLAY_NM { get; set; }
        public string ACTIVE_IND { get; set; }
        public System.DateTime CREATED_ON_DT { get; set; }
        public string CREATED_BY_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATED_ON_DT { get; set; }
        public string UPDATED_BY_USER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YES_ESTIMATE_COMMON> YES_ESTIMATE_COMMON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YES_LOG_TIME> YES_LOG_TIME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YES_LOG_TIME> YES_LOG_TIME1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YES_LOG_TIME> YES_LOG_TIME2 { get; set; }
    }
}
