//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YES_CUSTOMER
    {
        public int CUSTOMER_ID_SQ { get; set; }
        public string CUSTOMER_NM { get; set; }
        public string CUSTOMER_EMAIL_ID { get; set; }
        public string CONTACT_NUM { get; set; }
        public string CREATED_BY_USER_ID { get; set; }
        public System.DateTime CREATED_ON_DT { get; set; }
        public string UPDATED_BY_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATED_ON_DT { get; set; }
    }
}
