//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ggapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YES_Instrumentation
    {
        public string EMPLOYEE_ID { get; set; }
        public string USER_CURRENT_REGION { get; set; }
        public string TECHNOLOGY_CD { get; set; }
        public string TASK { get; set; }
        public string ELAPSED_TIME { get; set; }
    }
}
