SELECT O.ESTIMATE_ID_SQ, O.REQUEST_ESTIMATE_STATUS_CD,CONVERT(date,O.CREATED_ON_DT) AS CREATED_ON_Date, 
convert(date,O.UPDATED_ON_DT) as LAST_UPDATED,P.CUSTOMER_NM, 
I.LOCATION_NM,J.DISPLAY_NM 
  FROM [YES_ESTIMATE_COMMON] O 
  JOIN YES_LOCATION I ON O.LOCATION_ID = I.LOCATION_ID_SQ 
  JOIN YES_CUSTOMER P ON O.CUSTOMER_ID = P.CUSTOMER_ID_SQ
  JOIN YES_APPLICATION_USER J ON O.ESTIMATED_BY_ID = J.EMPLOYEE_ID
  where ((O.REQUEST_ESTIMATE_STATUS_CD = 'ISS' or O.REQUEST_ESTIMATE_STATUS_CD = 'COM'
  or O.REQUEST_ESTIMATE_STATUS_CD = 'IPRG')and O.CREATED_ON_DT > DATEADD(month, -24, GETDATE()));
